CREATE TABLE geo(
size VARCHAR(15) NOT NULL,
reach DECIMAL(4,0),
stack DECIMAL(4,0),
toptubeeffective DECIMAL(4,0),
toptubeactual DECIMAL(4,0),
seattubect DECIMAL(4,0),
seattubecc DECIMAL(4,0),
seattubeeffective DECIMAL(4,0),
seatpostdia DECIMAL(3,1),
seatpostlength DECIMAL(4,0),
seatpostmaxinsert DECIMAL(4,0),
seatangle DECIMAL(4,2),
headangle DECIMAL(4,2),
headtube DECIMAL(3,0),
headset VARCHAR(15),
chainstay DECIMAL(4,0),
wheelbase DECIMAL(5,0),
frontcenter DECIMAL(4,0),
standover DECIMAL(4,0),
bbdrop DECIMAL(3,0),
bbheight DECIMAL(3,0),
bbtype VARCHAR(30),
rake DECIMAL(2,0),
trail DECIMAL(2,0),
axletocrown DECIMAL(4,0),
axlespaceing DECIMAL(3,0),
fwheelsize ENUM('29', '27.5', '26', '24'),
rwheelsize ENUM('29', '27.5', '26', '24'),
tiremaxwidth DECIMAL(3,0),
handlebarwidth DECIMAL(4,1),
stemlength DECIMAL(3,0),
stemangle DECIMAL(4,2),
cranklength DECIMAL(3,0),
ftravel DECIMAL(3,0),
rtravel DECIMAL(3,0),
shocksize VARCHAR(15),
weight DECIMAL(4,2),
bid INT UNSIGNED,
FOREIGN KEY(bid) REFERENCES bike(id),
gid INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY);
